/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import javax.swing.JOptionPane;
import main.Shop;
import model.Employee;
import model.Person;
import Exception.LimitLoginException;

/**
 *
 * @author usuario
 */
public class LoginView extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(LoginView.class.getName());
    private int attempts = 0;
    private final int MAX_ATTEMPTS = 3;

    /**
     * Creates new form Login
     */
    public LoginView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pw_Empl_wr = new javax.swing.JTextField();
        Id_Empl = new javax.swing.JLabel();
        Id_Emp_wr = new javax.swing.JSpinner();
        Psw_Empl = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        Name_Emp = new javax.swing.JLabel();
        Name_Emp_wr = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pw_Empl_wr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Pw_Empl_wr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pw_Empl_wrActionPerformed(evt);
            }
        });

        Id_Empl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Id_Empl.setText("Numero de empleado");
        Id_Empl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Id_Emp_wr.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                Id_Emp_wrInputMethodTextChanged(evt);
            }
        });

        Psw_Empl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Psw_Empl.setText("Password");
        Psw_Empl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setBackground(new java.awt.Color(0, 204, 153));
        jButton1.setText("Acceder");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Name_Emp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Name_Emp.setText("Nombre");
        Name_Emp.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        Name_Emp_wr.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Name_Emp_wr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Name_Emp_wrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(30, 30, 30))
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Name_Emp_wr)
                    .addComponent(Id_Empl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Pw_Empl_wr)
                    .addComponent(Id_Emp_wr)
                    .addComponent(Psw_Empl, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
                    .addComponent(Name_Emp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(Name_Emp)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Name_Emp_wr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(Id_Empl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Id_Emp_wr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Psw_Empl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Pw_Empl_wr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pw_Empl_wrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pw_Empl_wrActionPerformed
        dispose();
    }//GEN-LAST:event_Pw_Empl_wrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    try {

        String name = Name_Emp_wr.getText();
        int user = (int) Id_Emp_wr.getValue();
        String pws = Pw_Empl_wr.getText();

        Employee emp = new Employee(user, pws, name);

        if (emp.login(user, pws)) {

            JOptionPane.showMessageDialog(this, "Login correcto");

            new ShopView().setVisible(true);
            this.dispose();

        } else {

            attempts++;

            JOptionPane.showMessageDialog(this, "Usuario o contraseña incorrectos");

            // Limpiar campos
            Name_Emp_wr.setText("");
            Pw_Empl_wr.setText("");
            Id_Emp_wr.setValue(0);

            if (attempts >= MAX_ATTEMPTS) {
                throw new LimitLoginException("Se ha alcanzado el número máximo intentos");
            }
        }

    } catch (LimitLoginException e) {

        JOptionPane.showMessageDialog(this, e.getMessage());
        System.exit(0); 

    } catch (Exception e) {

        JOptionPane.showMessageDialog(this, "Error en los datos");
    }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void Id_Emp_wrInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_Id_Emp_wrInputMethodTextChanged
        // TODO addour handling code here:
    }//GEN-LAST:event_Id_Emp_wrInputMethodTextChanged

    private void Name_Emp_wrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Name_Emp_wrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Name_Emp_wrActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner Id_Emp_wr;
    private javax.swing.JLabel Id_Empl;
    private javax.swing.JLabel Name_Emp;
    private javax.swing.JTextField Name_Emp_wr;
    private javax.swing.JLabel Psw_Empl;
    private javax.swing.JTextField Pw_Empl_wr;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
