/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.event.*;
import javax.swing.*;
import main.Shop;

/**
 *
 * @author usuario
 */
public class ShopView extends javax.swing.JFrame implements ActionListener, KeyListener {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ShopView.class.getName());
    
    private Shop shop;
    
    private JButton btnCash;
    private JButton btnAddProduct;
    private JButton btnAddStock;
    private JButton btnDeleteProduct;
    /**
     * Creates new form Menu
     */
    public ShopView() {
        
        initComponents();
        
        shop = new Shop();
//        shop.loadInventory(inventory);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        count_button = new javax.swing.JButton();
        addPr_button = new javax.swing.JButton();
        addSt_button = new javax.swing.JButton();
        deletePr_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        count_button.setText("1. Contar caja");
        count_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        count_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                count_buttonActionPerformed(evt);
            }
        });

        addPr_button.setText("2. Añadir producto");
        addPr_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addPr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPr_buttonActionPerformed(evt);
            }
        });

        addSt_button.setText("3. Añadir stock");
        addSt_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        addSt_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addSt_buttonActionPerformed(evt);
            }
        });

        deletePr_button.setText("9. Eliminar producto");
        deletePr_button.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deletePr_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletePr_buttonActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione o pulse una acción:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(count_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addPr_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(addSt_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deletePr_button, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(11, 11, 11))
                    .addComponent(jLabel1))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(70, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(count_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addPr_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addSt_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(deletePr_button)
                .addGap(63, 63, 63))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void count_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_count_buttonActionPerformed
    CashView cv = new CashView(this, true, shop);
    cv.setLocationRelativeTo(this);
    cv.setVisible(true);
//    this.dispose();
    }//GEN-LAST:event_count_buttonActionPerformed

    private void addPr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPr_buttonActionPerformed
        // TODO add your handling code here:
    ProductView pv = new ProductView(this, true, shop, 2); // "add" indica acción
    pv.setLocationRelativeTo(this);
    pv.setVisible(true);     
    }//GEN-LAST:event_addPr_buttonActionPerformed

    private void addSt_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addSt_buttonActionPerformed
    ProductView pv = new ProductView(this, true, shop, 3); // "stock" indica acción
    pv.setLocationRelativeTo(this);
    pv.setVisible(true);    // TODO add your handling code here:
    }//GEN-LAST:event_addSt_buttonActionPerformed

    private void deletePr_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletePr_buttonActionPerformed
        // TODO add your handling code here:
    ProductView pv = new ProductView(this, true, shop, 9); // "delete" indica acción
    pv.setLocationRelativeTo(this);
    pv.setVisible(true);
    }//GEN-LAST:event_deletePr_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ShopView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPr_button;
    private javax.swing.JButton addSt_button;
    private javax.swing.JButton count_button;
    private javax.swing.JButton deletePr_button;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void keyTyped(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void keyPressed(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    @Override
    public void keyReleased(KeyEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
